default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *default
